on:
  push:
    branches:
      - main
    paths:
      - "chaincodes/carbon/**"
      - ".github/workflows/chaincode.yaml"
  pull_request:
    branches:
      - main


jobs:
  build-test-chaincode:
    env:
      GOPRIVATE: github.com/${{ github.repository }}
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: chaincodes/carbon
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.24

      - name: Configure git for private modules
        env:
          TOKEN: ${{ github.token }}
        run: git config --global url."https://user:${TOKEN}@github.com".insteadOf "https://github.com"

      - name: Build carbon chaincode
        run: go mod tidy && go mod vendor && go build -o carbon ./cmd/carbon/main.go

      - name: Run the tests
        run: go test ./tests

  # I had to grant package access in: https://github.com/johannww?tab=packages
  docker-chaincode-build:
    env:
      GOPRIVATE: github.com/${{ github.repository }}
    needs: build-test-chaincode
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}
          logout: false

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ghcr.io/${{ github.repository }}/carbon

      - name: Configure git for private modules
        env:
          TOKEN: ${{ github.token }}
        run: git config --global url."https://user:${TOKEN}@github.com".insteadOf "https://github.com"

      - name: Vendor outside the container
        working-directory: chaincodes/carbon
        run: go mod tidy && go mod vendor

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          context: "chaincodes/carbon/"
          file: "chaincodes/carbon/Dockerfile"
          tags: ghcr.io/${{ github.repository }}/carbon:latest
          cache-from: type=registry,ref=ghcr.io/${{ github.repository }}/carbon:latest
          cache-to: type=inline

