on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main


jobs:
  build-chaincode:
    runs-on: ubuntu-latest
    # defaults:
      # run:
      #   working-directory: chaincodes/carbon
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.23

      - name: List directories
        run: pwd
      - name: List directories
        run: ls -la .

  # docker-build:
  #   needs: build
